repositories:
  - name: stable
    url: https://charts.helm.sh/stable 

  - name: jetstack
    url: https://charts.jetstack.io

  - name: habor 
    url: https://helm.goharbor.io

releases:
  - name: nginx-ingress
    createNamespace: true
    namespace: nginx-ingress
    chart: stable/nginx-ingress
    version: 1.41.3

  - name: cert-manager
    createNamespace: true
    namespace: cert-manager 
    chart: jetstack/cert-manager
    version: 0.16.1
    wait: true
    set:
    - name: installCRDs
      value: true

  - name: chartmuseum
    createNamespace: true  
    namespace: chartmuseum
    chart: stable/chartmuseum
    version: 2.13.2
    values:
      - ./values/chartmuseum.yaml

  - name: harbor
    createNamespace: true  
    namespace: harbor
    chart: harbor/harbor
    version: 1.1.2
    values:
      - ./values/harbor.yaml

