apiVersion: apps/v1
kind: Deployment 
metadata:
 name: paymentservice
 labels:
  app: paymentservice
spec:
 replicas: 3
 selector:
  matchLabels:
   tier: paymentservice
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxUnavailable: 0
   maxSurge: 100%
 template:
  metadata:
   labels:
    app: paymentservice
    tier: paymentservice
  spec:
   containers:
    - name: server
      image: horror894/controllers-hipster-shop-paymentservice:v0.0.2 
      ports:
       - containerPort: 50051      
      env:
       - name: PORT
         value: "50051"
