apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  replicas: 3
  template: 
    spec:
      containers:
      - name: server
        resources:
          requests:
            cpu: 300m
            memory: 128Mi
          limits:
            cpu: 600m
            memory: 256Mi
