apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
bases:
- ../../base

namePrefix: prod-
namespace: hipster-shop-prod
commonLabels:
    env: prod

patchesStrategicMerge:
- cartservice-deployment-v001.yaml

images:
- name: gcr.io/google-samples/microservices-demo/cartservice 
  newTag: v0.1.3
